### ISSUE TITLE
自動アップデートの挙動と停止

### ISSUE THREAD

**Issue by 888kk** [akameco/PixivDeck#111]
win 7 x64環境にて、ver0.14.2のwinアーカイブ版を使用しています。

ファイルを任意のディレクトリに展開して使用していたのですが、
本日2回ほど再起動させたところ、2回とも自動で0.14.3へのアップデートが始まってしまいました。
そのアップデートにより、
以下の2ヶ所のフォルダへ自動でインストールが行われてしまいました。
C:\Documents and Settings\"userフォルダ"\AppData\Local\Programs\PixivDeck
C:\Users\"userフォルダ"\AppData\Local\Programs\PixivDeck

任意のディレクトリでpixivdeckを使用したいので、設定等で自動アップデートを停止させる事はできませんか？

**Comment by akameco** [comment]
@888kk さんissueありがとうございます。

とりあえず自動アップデートを停止することを選択可能にする設定を次回バージョンに導入したいと思います。

しかし、2箇所にインストールされるのは奇妙ですね。
両方とも実行ファイルですか？

**Comment by 888kk** [comment]
ご対応ありがとうございます。
あるいは、インストール先を選択出来るようにはなりませんか？

2ヶ所とも実行ファイルでしたが、
片方でUninstall PixivDeck.exeを実行すると両方とも削除されました。

**Comment by akameco** [comment]
調査したところ、自動更新に使用してるライブラリのオプションで任意のディレクトリにインストール可能であることがわかりました。

related https://github.com/electron-userland/electron-builder/issues/596

本日中にこの変更を適用してリリースします。

**Comment by akameco** [comment]
v0.14.5で任意の場所にインストールする設定に変更しました。
インストーラーを利用してインストールすることで、自動アップデートが適切なパスに設定されるはずです。

https://github.com/akameco/PixivDeck/releases/tag/v0.14.5
