### ISSUE TITLE
Wrong locale detected.

### ISSUE THREAD

**Issue by trnhoe** [akameco/PixivDeck#130]
[navigator.language](https://github.com/akameco/PixivDeck/blob/3c9898b6faf4fb595b7b6b27210f30e4364845f8/app/containers/Language/index.js#L25) does not work well. It is still 'en-US' however I have changed the system locale to another.
I found [app.getLocale()](https://electron.atom.io/docs/api/locales/) might work.

Thanks. :-p

**Comment by akameco** [comment]
Thank you @trnhoe :)
Make sense.

Could you send the Pull Request?

**Comment by akameco** [comment]
Fixed #132
