### ISSUE TITLE
ver16以降のプラットフォームについて

### ISSUE THREAD

**Issue by 888kk** [akameco/PixivDeck#137]
16.1の更新ありがとうございます。
downloadリンクがmac版のみになっていますが、
win版の対応は終了したのでしょうか？

**Comment by akameco** [comment]
@888kk 
いつも使っていただきありがとうございます！
すいません。こちらのミスです。
自動リリースをしているので、気づきませんでした。
調査して、近日中にwindows版も公開します。
報告ありがとうございました。

**Comment by akameco** [comment]
修正し、v0.16.3としてリリースしました 🎉 

https://github.com/akameco/PixivDeck/releases/tag/v0.16.3

報告ありがとうございました！
