### ISSUE TITLE
App blank page on next launch when closing with an illustration open

### ISSUE THREAD

**Issue by austinhuang0131** [akameco/PixivDeck#152]
Might relate to #146 and #148.

## Steps
1. Open PixivDeck.
2. Click on an illustration to see its enlarged version.
3. Cmd+Q to quit PixivDeck **without closing the enlarged image**.
4. Reopen PixivDeck. A blank page will be shown. Cmd+R will not resolve it.

I can forcibly resolve this every time by deleting `~/Library/Application Support/PixivDeck`, however it wipes all storage so it's not an ideal solution.

## Versions
* PixivDeck 0.16.3
* Electron 1.7.8
* darwin x64 15.6.0

**Comment by akameco** [comment]
Fixed #165
