### ISSUE TITLE
1.0.3が正常に起動しない

### ISSUE THREAD

**Issue by sachin21** [akameco/PixivDeck#168]
- module name:
  - :question:
- module version:
  - :question: 
- `node` version:
  - `v9.11.1`
- `yarn` version:
  `1.7.0`

**Do you want to request a _feature_ or report a _bug_?:**

1.0.3の起動に失敗します。

**What is the current behavior?:**
```
$ PixivDeck-1.0.3-x86_64.AppImage
Skip loading 'React Developer Tools' because it can't be found. Please install at Chrome Web Store.
Skip loading 'Redux DevTools' because it can't be found. Please install at Chrome Web Store.
[15:06:20.615] [info] Checking for update
[15:06:23.262] [info] Update for version 1.0.3 is not available (latest version: 1.0.3, downgrade is disallowed).
```

というmessageが出て正常に起動しません。

**What is the expected behavior?:**

ログイン画面、もしくはカラム一覧が出てくることを期待する。

**What is the suggested solution?:**

補足情報ですが、私が試したversionは`1.0.3`と`1.0.2`になります。
少無くとも`1.0.2`から発生していると思います。

## Additional environment information

- `$ uname --kernel-name --machine --operating-system`
  - `Linux x86_64 GNU/Linux`

**Comment by sachin21** [comment]
akamecoさんの方では正常に起動していますでしょうか？(Linuxのbuildがコケているのだろうか・・

**Comment by akameco** [comment]
@sachin21 あーすいません :pray:
わかりました。
修正しておきます。

**Comment by sachin21** [comment]
なるほどー、ありがとうございます！！

**Comment by sachin21** [comment]
> https://github.com/akameco/PixivDeck/commit/04c41a2e2189f9f5811aafd17fbe882d05877f47

@akameco 上記のcommitが含まれているはずの`v1.0.7`をインストールしましたが、以前動作は`v1.0.3`と変わらずなんですが、 @akameco さんの手元では動作していますか？

**Comment by akameco** [comment]
@sachin21 報告ありがとうございます。なぜか自分の手元だと動いてて再現しないんですよね 🤔 開発がMacでlinux環境を用意してないので、何か環境特有のバグがあるのかも知れません。

**Comment by sachin21** [comment]
Hmm. なるほど。問題が発生しているのはLinux PCとWindows PCです。
yarn devではこの問題は発生しないんですが、releasesからダウンロードして起動すると遭遇します。
一旦一旦Windows PCでインストールしてみましたが、それでも再現しました :bowing_man: 
@akameco さんは最新の`v1.0.7`をreleasesからダウンロードして使っていますか？

**Comment by akameco** [comment]
<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="ja" dir="ltr">まっさらな状態で試すと普通に起動しました。おそらくキャッシュまわりでおかしくなっている気がします。Windowsの場合はC:\Users\YourPCName\%APPDATA%PixivDeck を削除してみてください</p>&mdash; あかめ@地獄への道は善意で舗装されている.js (@akameco) <a href="https://twitter.com/akameco/status/1045253533056946177?ref_src=twsrc%5Etfw">September 27, 2018</a></blockquote>

キャッシュの問題だったのでクローズします

**Comment by sachin21** [comment]
ありがとうございました！
