### ISSUE TITLE
change default locale language

### ISSUE THREAD

**Issue by zoghal** [akameco/PixivDeck#18]
hi 
How do I set the  locale language on the English?
-

PixivDeck 0.12.1
Electron 1.6.0
win32 ia32 10.0.14393

**Comment by akameco** [comment]
@zoghal Thank you for your reporting.

Currently only Japanese is supported.
I will try multilingual support at the weekend.

**Comment by volcbs** [comment]
Dev-san?
Any news for this?

**Comment by akameco** [comment]
You can change locale here. (ここで設定できます。)

![2017-07-03 03 45 22](https://user-images.githubusercontent.com/4002137/27772678-13a18576-5fa2-11e7-834b-1577e024f76f.png)

My weak point is English. I am happy if you correct English with PR. (英語が苦手なので、修正のPRを送ってくれると嬉しいです。)

https://github.com/akameco/PixivDeck/blob/master/app/i18n/en.yml

**Comment by nguyenvancaoky** [comment]
it not work ! http://s26.postimg.org/54nj06c15/screenshot_25.png

**Comment by akameco** [comment]
@nguyenvancaoky what app version?

**Comment by nguyenvancaoky** [comment]
@akameco  version 0.13.4

**Comment by akameco** [comment]
@nguyenvancaoky 
Type `F12`, to open developer tool.
and open Console tab.
have Errors?

![2017-07-05 00 23 31](https://user-images.githubusercontent.com/4002137/27836008-7e64400c-6118-11e7-9c9c-8462a2b9b311.png)

**Comment by volcbs** [comment]
It works great in 0.13.22
Thanks!

**Comment by akameco** [comment]
Thank you for the advice!

I will change the translation.

> Anyway, well, it's out of topic but will you add 'recommend for you' or 'あなたにおすすめ' feature? It's very useful to see content that is similar to your taste.

Ok. I will consider it.

**Comment by nguyenvancaoky** [comment]
@akameco 
no errors.
https://i.imgur.com/Mb9lYRR.png
