### ISSUE TITLE
pixivで開くの動作

### ISSUE THREAD

**Issue by 888kk** [akameco/PixivDeck#20]
win7 64bit
ver0.12.1
上記の環境で使用しております。

数日前に0.12.1に更新したのですが、
コンテキストメニューの「pixivで開く」が動作しません。
以前のバージョンでは外部ブラウザで作品のページが開いたのですが、
他に何か設定等が必要になるのでしょうか？

-

PixivDeck 0.12.1
Electron 1.6.0
win32 ia32 6.1.7601

**Comment by akameco** [comment]
@888kk 報告ありがとうございます！
現状、自分の環境では再現しません(正常に外部ブラウザで開きます)。
少し調査をする必要がありそうです。
解決まで以前のバージョンを使ってくださると助かります。

**Comment by 888kk** [comment]
その後、0.12.1で
C:\Users\ユーザー名\AppData\Roaming\PixivDeck以下を消してみたり
一度既存のフォルダを消して0.12.1を新規インストールしてみましたが、
pixivで開くは動作しませんでした。

0.11.0を入れなおしてみましたが、こちらですと外部ブラウザで正常に開きます

**Comment by akameco** [comment]
最新版ではどうですか？
よろしければ確認お願いします。

**Comment by 888kk** [comment]
アーカイブ版の対応ありがとうございました。
11.0から最新版へ更新したところ、
規定のブラウザで開けるようになりました。

**Comment by akameco** [comment]
それはよかったです 🎉 

解決したのでクローズします。
