### ISSUE TITLE
Cannot login via twitter

### ISSUE THREAD

**Issue by NO-ob** [akameco/PixivDeck#281]
- module name: PixivDeck-1.4.0-x86_64.AppImage 
- module version: 1.4.0
- `node` version: ?
- `yarn` version: ?
  

Do you want to request a _feature_ or report a _bug_?: may be a bug or feature not sure

What is the current behavior?: Cant login as my pixiv account uses a twitter login, i have tried using my username and email both dont work

What is the expected behavior?: Ability to log in

What is the suggested solution?: Twitter login support

**Comment by akameco** [comment]
@NO-ob Thank you for the issue. However, I can't implement it because I don't have time. sorry
