### ISSUE TITLE
Login error without any hint!

### ISSUE THREAD

**Issue by FlandreDaisuki** [akameco/PixivDeck#4]
When I login with invalid account, it can get into the main page without any hint...
It should keep user at login page or get some hint to let user know.
## 

PixivDeck 0.3.0
Electron 1.3.5
linux x64 4.4.0-38-generic

**Comment by akameco** [comment]
Thank you @FlandreDaisuki :)
I fixed it.

![2016-11-06 17 22 36](https://cloud.githubusercontent.com/assets/4002137/20036690/9ac6e584-a452-11e6-96be-466a40d830f5.png)
