### ISSUE TITLE
Can't login !

### ISSUE THREAD

**Issue by nguyenvancaoky** [akameco/PixivDeck#52]
-

			PixivDeck 0.13.4
			Electron 1.6.11
			win32 x64 10.0.15063

**Comment by akameco** [comment]
Oh, Sorry.

Try remove chace.

`C:\Users\YourPCName\%APPDATA%PixivDeck`

related #6

**Comment by nguyenvancaoky** [comment]
@akameco  It work ! Thank you 👍
