### ISSUE TITLE
pixiv側のパスを変更したら…

### ISSUE THREAD

**Issue by 888kk** [akameco/PixivDeck#6]
windows7環境にて、pixivdeckを使わせてもらってます。

先ほどブラウザからpixivのログインパスを変更したところ、pixivdeckが使えなくなりました。
アプリを再起動してもウインドウが一面真っ白になり何も読み込みません。
pixivdeck側のパス変更への対応はどうしたらいいでしょうか？

お手数ですが、よろしくお願いします。

**Comment by akameco** [comment]
報告ありがとうございます。
ログインパスワードの変更を考慮してませんでした。
のちのち修正しますが、今現在の一時的な修正としては、PixivDeckの設定ファイルを消去する方法があります。

PixivDeckを起動しないまま、`C:\Users\ユーザー名\%APPDATA%`にある`PixivDeck`フォルダを削除してみてください。

ただ、追加してカラムも初期化されてしまうのでご注意ください。

**Comment by akameco** [comment]
報告ありがとうございました！
また何かあったら報告お願いします :)
