### ISSUE TITLE
ver0.13以降…

### ISSUE THREAD

**Issue by 888kk** [akameco/PixivDeck#83]
ver0.13以降のwindows版について、
zipなどのアーカイブ形式での配布は行ってないですか？
Setup-0.13.xx.exeのインストーラー形式のみの配布でしょうか？

**Comment by akameco** [comment]
@888kk さんissueありがとうございます。

v0.13からリリース処理手元で行わずをCIより自動リリースに切り替えました。
その際、自動リリースのデフォルトの設定に寄せたので、アーカイブ形式での配信がなくなってしまったようです。

現状は.exeのみの配信のつもりですが、何か不都合がありますか？
もし不都合があれば次回リリース時から、アーカイブ形式も追加したいと思います。

**Comment by akameco** [comment]
https://github.com/akameco/PixivDeck/releases/tag/v0.13.18

v0.13.18リリースしました。
zip形式と7z形式を追加しました。
